discussion_s01/discussion_s01/Models/ErrorViewModel.cs
namespace discussion_s01.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

discussion_s01/discussion_s01/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;

namespace discussion_s01.Controllers
{
    public class CoursesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateCourse()
        {
            return View();
        }
    }
}

discussion_s01/discussion_s01/Controllers/HomeController.cs
using discussion_s01.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace discussion_s01.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

discussion_s01/discussion_s01/Views/Courses/CreateCourse.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Create Courses Page";
}
<h1>Create New Course</h1>
<form class="d-flex flex-column">
    <div class="form-group my-2">
        <label for="course-name">
            <span class="d-inline-block" style="width:150px;">Course Title:</span>
            <input type="text" name="course-name" id="course-name" class="d-inline-block" style="width:200px;" />
        </label>
    </div>
    <div class="form-group my-2">
        <label for="stack">
            <span class="d-inline-block" style="width:150px;">Stack:</span>
            <select id="stack" class="d-inline-block" style="width:200px;">
                <option value="mern-stack">MERN Stack</option>
                <option value="mean-stack">MEAN Stack</option>
                <option value="django-stack">Django Stack</option>
                <option value="rails">Rails</option>
                <option value="lamp-stack">LAMP Stack</option>
            </select>
        </label>
    </div>
    <div class="form-group my-2">
        <label for="description">
            <span class="d-inline-block" style="width:150px;">Description:</span>
            <input type="text" name="description" id="description" class="d-inline-block" style="width:200px;" />
        </label>
    </div>
    <div class="form-group my-2">
        <label for="thumbnail">
            <span class="d-inline-block" style="width:150px;">Thumbnail:</span>
            <input type="text" name="thumbnail" id="thumbnail" class="d-inline-block" style="width:200px;" />
        </label>
    </div>
    <div class="form-group my-2">
        <label for="price">
            <span class="d-inline-block" style="width:150px;">Price:</span>
            <input type="number" name="price" id="price" class="d-inline-block" style="width:200px;" />
        </label>
    </div>
    <div style="margin-left: 150px;">
        <button type="submit" class="btn btn-primary d-block ml-5" style="width:200px;">Create</button>
    </div>
</form>

discussion_s01/discussion_s01/Views/Courses/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Courses Page";
}

<div class="text-center mb-5">
    <h1 class="display-4">
        Welcome to LaZuitt
    </h1>
    <br />
    <h3>Hello, Admin</h3>
</div>

<div class="d-flex justify-content-between mb-3">
    <h2 class="d-inline">Courses Available</h2>
    <button class="btn btn-secondary text-light">
        <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="CreateCourse">
            Create Course
        </a>
    </button>
</div>

<div class="row d-flex justify-content-between">
    <div class="card bg-white p-3 text-center" style="width: 22.5%; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2)">
        <h3>ASP.NET</h3>
        <img class="img-fluid h-50" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMOH00P2p0cF3CtYyLLUp_7yTJsoqpwIyxeUihYWnOszvwSbFcJbyv3NleB4ackTfap2I&usqp=CAU" />

        <p>ASP is a development framework for building web pages.</p>

        <div class="d-flex flex-column justify-content-center align-items-center">
            <button class="mb-2 btn btn-primary w-100">Edit</button>
            <button class="mb-2 btn btn-info w-100">Details</button>
            <button class="mb-2 btn btn-danger w-100">Delete</button>
        </div>

    </div>

    <div class="card bg-white p-3 text-center" style="width: 22.5%; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2)">
        <h3>Python</h3>
        <img class="img-fluid h-50" src="https://i.pinimg.com/originals/a8/53/14/a8531424a5fac660e4261f72ca817141.png" />

        <p>Python can be used on a server to create web applications.</p>

        <div class="d-flex flex-column justify-content-center align-items-center">
            <button class="mb-2 btn btn-primary w-100">Edit</button>
            <button class="mb-2 btn btn-info w-100">Details</button>
            <button class="mb-2 btn btn-danger w-100">Delete</button>
        </div>

    </div>

    <div class="card bg-white p-3 text-center" style="width: 22.5%; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2)">
        <h3>Django</h3>
        <img class="img-fluid h-50" src="https://youteam.io/blog/wp-content/uploads/2022/06/django-icon-0.png" />

        <p>Django is a Python framework that makes it easier to create websites using Python.</p>

        <div class="d-flex flex-column justify-content-center align-items-center">
            <button class="mb-2 btn btn-primary w-100">Edit</button>
            <button class="mb-2 btn btn-info w-100">Details</button>
            <button class="mb-2 btn btn-danger w-100">Delete</button>
        </div>

    </div>

    <div class="card bg-white p-3 text-center" style="width: 22.5%; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2)">
        <h3>JavaScript</h3>
        <img class="img-fluid h-50" src="https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png" />

        <p>JavaScript is the most known programming language of the web</p>

        <div class="d-flex flex-column justify-content-center align-items-center">
            <button class="mb-2 btn btn-primary w-100">Edit</button>
            <button class="mb-2 btn btn-info w-100">Details</button>
            <button class="mb-2 btn btn-danger w-100">Delete</button>
        </div>

    </div>
     
</div>

discussion_s01/discussion_s01/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to LaZuitt</h1>
    <br />
</div>

<div class="text-center">
    <button style="float: center; background-color: #e1f5fe; border-radius: 10px">
        @* In the anchor tag, the "asp-controller" is used to define the controller file to be used when clicking on the link, the "asp-action" refers to the method to be executed in the controller to render the view page. *@
        <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">
            Manage Courses
        </a>
    </button>
</div>

discussion_s01/discussion_s01/Views/Settings/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Settings";
}